import "./globals.css";
import { EdgeStoreProvider } from "@/lib/edgestore";
import AuthProvider from "@/providers/AuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer";
import { getCurrentUser } from "@/actions/getCurrentUser";
import { User } from "@/types/users";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <EdgeStoreProvider>
            <div className="main-container">
              <div className="wrapper">
                <Navbar user={user as User} />
                {children}
                <Footer />
              </div>
            </div>
          </EdgeStoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
